# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Internship/HDL/hdl/projects/common/zyboz7/zyboz7_system_constr.xdc

# XDC: c:/Internship/hdl/hdl/projects/ad5592r_pmdz/zyboz7/system_constr.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_sys_ps7_0/system_sys_ps7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_ps7_0 || ORIG_REF_NAME==system_sys_ps7_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_concat_intc_0/system_sys_concat_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_concat_intc_0 || ORIG_REF_NAME==system_sys_concat_intc_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_sysid_0_0/system_axi_sysid_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_sysid_0_0 || ORIG_REF_NAME==system_axi_sysid_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rom_sys_0_0/system_rom_sys_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rom_sys_0_0 || ORIG_REF_NAME==system_rom_sys_0_0} -quiet] -quiet

# IP: bd/system/ip/system_GND_1_0/system_GND_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_GND_1_0 || ORIG_REF_NAME==system_GND_1_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_cpu_interconnect_0/system_axi_cpu_interconnect_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_cpu_interconnect_0 || ORIG_REF_NAME==system_axi_cpu_interconnect_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_pwm_led_generator_0/system_axi_pwm_led_generator_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_pwm_led_generator_0 || ORIG_REF_NAME==system_axi_pwm_led_generator_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: c:/Internship/hdl/hdl/projects/ad5592r_pmdz/zyboz7/ad5592r_zyboz7.gen/sources_1/bd/system/system_ooc.xdc
