# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Internship/hdl/hdl/projects/ad5592r_pmdz/zyboz7/ad5592r_zyboz7.srcs/sources_1/bd/system/ip/system_axi_pwm_led_generator_0/system_axi_pwm_led_generator_0.xci
# IP: The module: 'system_axi_pwm_led_generator_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Internship/hdl/hdl/projects/ad5592r_pmdz/zyboz7/ad5592r_zyboz7.gen/sources_1/bd/system/ip/system_axi_pwm_led_generator_0/axi_pwm_custom.srcs/sources_1/ip/my_ila/my_ila.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==my_ila || ORIG_REF_NAME==my_ila} -quiet] -quiet

# XDC: c:/Internship/hdl/hdl/projects/ad5592r_pmdz/zyboz7/ad5592r_zyboz7.gen/sources_1/bd/system/ip/system_axi_pwm_led_generator_0/axi_pwm_custom.srcs/sources_1/ip/my_ila/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==my_ila || ORIG_REF_NAME==my_ila} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Internship/hdl/hdl/projects/ad5592r_pmdz/zyboz7/ad5592r_zyboz7.gen/sources_1/bd/system/ip/system_axi_pwm_led_generator_0/axi_pwm_custom.srcs/sources_1/ip/my_ila/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==my_ila || ORIG_REF_NAME==my_ila} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Internship/hdl/hdl/projects/ad5592r_pmdz/zyboz7/ad5592r_zyboz7.gen/sources_1/bd/system/ip/system_axi_pwm_led_generator_0/axi_pwm_custom.srcs/sources_1/ip/my_ila/my_ila_ooc.xdc

# XDC: c:/Internship/hdl/hdl/projects/ad5592r_pmdz/zyboz7/ad5592r_zyboz7.gen/sources_1/HDL/hdl/library/xilinx/common/up_xfer_cntrl_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_pwm_led_generator_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Internship/hdl/hdl/projects/ad5592r_pmdz/zyboz7/ad5592r_zyboz7.gen/sources_1/HDL/hdl/library/xilinx/common/up_xfer_status_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_pwm_led_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Internship/hdl/hdl/projects/ad5592r_pmdz/zyboz7/ad5592r_zyboz7.srcs/sources_1/bd/system/ip/system_axi_pwm_led_generator_0/system_axi_pwm_led_generator_0.xci
# IP: The module: 'system_axi_pwm_led_generator_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Internship/hdl/hdl/projects/ad5592r_pmdz/zyboz7/ad5592r_zyboz7.gen/sources_1/bd/system/ip/system_axi_pwm_led_generator_0/axi_pwm_custom.srcs/sources_1/ip/my_ila/my_ila.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==my_ila || ORIG_REF_NAME==my_ila} -quiet] -quiet

# XDC: c:/Internship/hdl/hdl/projects/ad5592r_pmdz/zyboz7/ad5592r_zyboz7.gen/sources_1/bd/system/ip/system_axi_pwm_led_generator_0/axi_pwm_custom.srcs/sources_1/ip/my_ila/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==my_ila || ORIG_REF_NAME==my_ila} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Internship/hdl/hdl/projects/ad5592r_pmdz/zyboz7/ad5592r_zyboz7.gen/sources_1/bd/system/ip/system_axi_pwm_led_generator_0/axi_pwm_custom.srcs/sources_1/ip/my_ila/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==my_ila || ORIG_REF_NAME==my_ila} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Internship/hdl/hdl/projects/ad5592r_pmdz/zyboz7/ad5592r_zyboz7.gen/sources_1/bd/system/ip/system_axi_pwm_led_generator_0/axi_pwm_custom.srcs/sources_1/ip/my_ila/my_ila_ooc.xdc

# XDC: c:/Internship/hdl/hdl/projects/ad5592r_pmdz/zyboz7/ad5592r_zyboz7.gen/sources_1/HDL/hdl/library/xilinx/common/up_xfer_cntrl_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_pwm_led_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Internship/hdl/hdl/projects/ad5592r_pmdz/zyboz7/ad5592r_zyboz7.gen/sources_1/HDL/hdl/library/xilinx/common/up_xfer_status_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_pwm_led_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
